name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: 'Docker Registry Login' 
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: 'Pull Docker Image'    
        shell: bash
        run: |
          docker pull docker.pkg.github.com/icn-team/android-build/hicn:latest
      - name: 'Build apks'
        shell: bash
        run: |
          docker run -v $PWD:/hicn  docker.pkg.github.com/icn-team/android-build/hicn bash -c "bash /hicn/build_apk.sh"; mkdir -p apks; cp *.apk apks/
      - name: 'Push Apks artifacts'
        uses: actions/upload-artifact@v1
        with:
          name: apks
          path: apks
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Android Application ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload Release Asset (hICN_Tools)
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apks/hICN_Tools.apk
          asset_name: hICN_Tools.apk
          asset_content_type: application/zip
      - name: Upload Release Asset (HicnForwarderAndroid)
        id: upload-release-asset-hicnforwarder
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apks/HicnForwarderAndroid.apk
          asset_name: HicnForwarderAndroid.apk
          asset_content_type: application/zip
     
