name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: 'Docker Registry Login' 
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: 'Pull Docker Image'    
        shell: bash
        run: |
          docker pull docker.pkg.github.com/icn-team/android-build/hicn:latest
      - name: 'Build apks'
        shell: bash
        run: |
          docker run -v $PWD:/hicn  docker.pkg.github.com/icn-team/android-build/hicn bash -c "bash /hicn/build_apk.sh"
      - name: 'Push Apks artifacts'
        uses: actions/upload-artifact@v1
        with:
          name: apks
          path: '*.apk'
      - name: 'Curl'
        shell: bash
        run: |
          curl -X POST -d 'name=HicnForwarderAndroid.apk’ https://uploads.github.com/repos/icn-team/android-sdk/releases/1/assets
